name: mongo-sharding
services:

  # api
  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

  # сервер конфигурации
  configSrv:
    image: mongo:latest
    container_name: cconfigSrv
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command: mongod --configsvr --replSet config-server --bind_ip_all --port 27017
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command: mongos --configdb config-server/configSrv:27017 --bind_ip_all --port 27020
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # 1-й шард
  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # 2-й шард
  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-data:/data/db
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

volumes:
  config-data:
  config-data-configdb:
  shard1-data:
  shard2-data: